name: Build and Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: deploy
        run:  sh deploy.sh ${{ secrets.ACCESS_TOKEN }}