name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: deploy
        run: |
          yarn install
          yarn build
          cd docs/.vuepress/dist
          git config --global user.name 'xdushepherd91'
          git config --global user.email 'xdushepherd91@gmail.com'
          git init
          git add -A
          git commit -m "deploy"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/vue-blog.git
          git push -f origin master:gh-pages
